In [132]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.linear_model import LinearRegression,LogisticRegression
from sklearn.model_selection import _split
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [133]:
titanic=pd.read_csv('titanic_train.csv')

In [134]:
titanic
print(titanic.shape)

(891, 12)


In [135]:
titanic['Cabin']
def checking_blank(column):
    count=0
    for i in titanic[column]:
        #print(i)
        if str(i)=='nan':
            count+=1
    return count        
print(checking_blank('Cabin'))         

687


In [6]:
titanic['Name'].unique()
len(titanic['Name'].unique())

891

In [7]:
titanic=titanic.drop(columns='Name')

In [8]:
titanic.shape

(891, 11)

In [9]:
titanic=titanic.drop(columns='PassengerId')

In [10]:
titanic

Survived  Pclass     Sex   Age  SibSp  Parch            Ticket     Fare  \
0           0       3    male  22.0      1      0         A/5 21171   7.2500   
1           1       1  female  38.0      1      0          PC 17599  71.2833   
2           1       3  female  26.0      0      0  STON/O2. 3101282   7.9250   
3           1       1  female  35.0      1      0            113803  53.1000   
4           0       3    male  35.0      0      0            373450   8.0500   
..        ...     ...     ...   ...    ...    ...               ...      ...   
886         0       2    male  27.0      0      0            211536  13.0000   
887         1       1  female  19.0      0      0            112053  30.0000   
888         0       3  female   NaN      1      2        W./C. 6607  23.4500   
889         1       1    male  26.0      0      0            111369  30.0000   
890         0       3    male  32.0      0      0            370376   7.7500   

    Cabin Embarked  
0     NaN        S  
1     C85        C  
2     NaN        S  
3    C123        S  
4     NaN        S  
..    ...      ...  
886   NaN        S  
887   B42        S  
888   NaN        S  
889  C148        C  
890   NaN        Q  

[891 rows x 10 columns]

In [11]:
print(len(titanic['Age'].unique()))
print(len(titanic['Ticket'].unique()))
print(len(titanic['Cabin'].unique()))
print(len(titanic['Embarked'].unique()))
print(len(titanic['Fare'].unique()))
print(len(titanic['Parch'].unique()))

89
681
148
4
248
7


In [12]:
print(checking_blank('Age'))
print(checking_blank('SibSp'))
print(checking_blank('Parch'))
print(checking_blank('Ticket'))
print(checking_blank('Fare'))
#print(checking_blank('Cabin'))
print(checking_blank('Sex'))
print(checking_blank('Embarked'))

177
0
0
0
0
0
2


In [13]:
ticket=LabelEncoder()
titanic['Tickets']=ticket.fit_transform(titanic['Ticket'])

In [14]:
titanic=titanic.drop(columns='Cabin')

In [15]:
print(len(titanic['Tickets'].unique()))
titanic=titanic.dropna(subset=['Embarked'])

681


In [16]:
embark=LabelEncoder()
titanic['Embarkeds']=embark.fit_transform(titanic['Embarked'])

In [17]:
titanic['Embarked']

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 889, dtype: object

In [18]:
titanic

Survived  Pclass     Sex   Age  SibSp  Parch            Ticket     Fare  \
0           0       3    male  22.0      1      0         A/5 21171   7.2500   
1           1       1  female  38.0      1      0          PC 17599  71.2833   
2           1       3  female  26.0      0      0  STON/O2. 3101282   7.9250   
3           1       1  female  35.0      1      0            113803  53.1000   
4           0       3    male  35.0      0      0            373450   8.0500   
..        ...     ...     ...   ...    ...    ...               ...      ...   
886         0       2    male  27.0      0      0            211536  13.0000   
887         1       1  female  19.0      0      0            112053  30.0000   
888         0       3  female   NaN      1      2        W./C. 6607  23.4500   
889         1       1    male  26.0      0      0            111369  30.0000   
890         0       3    male  32.0      0      0            370376   7.7500   

    Embarked  Tickets  Embarkeds  
0          S      523          2  
1          C      596          0  
2          S      669          2  
3          S       49          2  
4          S      472          2  
..       ...      ...        ...  
886        S      101          2  
887        S       14          2  
888        S      675          2  
889        C        8          0  
890        Q      466          1  

[889 rows x 11 columns]

In [19]:
se=LabelEncoder()
titanic['sex']=se.fit_transform(titanic['Sex'])

In [20]:
titanic

Survived  Pclass     Sex   Age  SibSp  Parch            Ticket     Fare  \
0           0       3    male  22.0      1      0         A/5 21171   7.2500   
1           1       1  female  38.0      1      0          PC 17599  71.2833   
2           1       3  female  26.0      0      0  STON/O2. 3101282   7.9250   
3           1       1  female  35.0      1      0            113803  53.1000   
4           0       3    male  35.0      0      0            373450   8.0500   
..        ...     ...     ...   ...    ...    ...               ...      ...   
886         0       2    male  27.0      0      0            211536  13.0000   
887         1       1  female  19.0      0      0            112053  30.0000   
888         0       3  female   NaN      1      2        W./C. 6607  23.4500   
889         1       1    male  26.0      0      0            111369  30.0000   
890         0       3    male  32.0      0      0            370376   7.7500   

    Embarked  Tickets  Embarkeds  sex  
0          S      523          2    1  
1          C      596          0    0  
2          S      669          2    0  
3          S       49          2    0  
4          S      472          2    1  
..       ...      ...        ...  ...  
886        S      101          2    1  
887        S       14          2    0  
888        S      675          2    0  
889        C        8          0    1  
890        Q      466          1    1  

[889 rows x 12 columns]

In [21]:
titanic=titanic.drop(columns=['Ticket','Embarked','Sex'])

In [22]:
titanic

Survived  Pclass   Age  SibSp  Parch     Fare  Tickets  Embarkeds  sex
0           0       3  22.0      1      0   7.2500      523          2    1
1           1       1  38.0      1      0  71.2833      596          0    0
2           1       3  26.0      0      0   7.9250      669          2    0
3           1       1  35.0      1      0  53.1000       49          2    0
4           0       3  35.0      0      0   8.0500      472          2    1
..        ...     ...   ...    ...    ...      ...      ...        ...  ...
886         0       2  27.0      0      0  13.0000      101          2    1
887         1       1  19.0      0      0  30.0000       14          2    0
888         0       3   NaN      1      2  23.4500      675          2    0
889         1       1  26.0      0      0  30.0000        8          0    1
890         0       3  32.0      0      0   7.7500      466          1    1

[889 rows x 9 columns]

In [23]:
print(checking_blank('Age'))
print(checking_blank('SibSp'))
print(checking_blank('Parch'))
print(checking_blank('Tickets'))
print(checking_blank('Fare'))
#print(checking_blank('Cabin'))
print(checking_blank('sex'))
print(checking_blank('Embarkeds'))

177
0
0
0
0
0
0


In [24]:
titanic_predict_for_age=titanic[titanic.isnull().any(axis=1)]

In [25]:
titanic_train_for_age=titanic.dropna()

In [26]:
titanic_train_for_age

Survived  Pclass   Age  SibSp  Parch     Fare  Tickets  Embarkeds  sex
0           0       3  22.0      1      0   7.2500      523          2    1
1           1       1  38.0      1      0  71.2833      596          0    0
2           1       3  26.0      0      0   7.9250      669          2    0
3           1       1  35.0      1      0  53.1000       49          2    0
4           0       3  35.0      0      0   8.0500      472          2    1
..        ...     ...   ...    ...    ...      ...      ...        ...  ...
885         0       3  39.0      0      5  29.1250      480          1    0
886         0       2  27.0      0      0  13.0000      101          2    1
887         1       1  19.0      0      0  30.0000       14          2    0
889         1       1  26.0      0      0  30.0000        8          0    1
890         0       3  32.0      0      0   7.7500      466          1    1

[712 rows x 9 columns]

In [71]:
y=titanic_train_for_age.iloc[:,2]
x=titanic_train_for_age.drop(columns=['Age'])

In [57]:
x
scaler=StandardScaler()
scaled_titanic_x_age=scaler.fit_transform(x)
y=np.array(y)
y=y.reshape(-1,1)
scaled_titanic_y_age=scaler.fit_transform(y)
scaled_titanic_x_age

array([[-0.82416338,  0.90859974,  0.52251079, ...,  0.92007841,
         0.51958818,  0.75613751],
       [ 1.21335165, -1.48298257,  0.52251079, ...,  1.27975046,
        -2.04948671, -1.32251077],
       [ 1.21335165,  0.90859974, -0.55271372, ...,  1.63942251,
         0.51958818, -1.32251077],
       ...,
       [ 1.21335165, -1.48298257, -0.55271372, ..., -1.5877719 ,
         0.51958818, -1.32251077],
       [ 1.21335165, -1.48298257, -0.55271372, ..., -1.61733399,
        -2.04948671,  0.75613751],
       [-0.82416338,  0.90859974, -0.55271372, ...,  0.63923859,
        -0.76494927,  0.75613751]])

In [95]:
x_train,x_test,y_train,y_test=_split.train_test_split(x,y,test_size=0.1,random_state=78)

In [96]:
model=LinearRegression(n_jobs=40)
model.fit(x_train,y_train)

y_pred=model.predict(x_test)
score=model.score(x_test,y_test)
score

0.0808411951667859

In [97]:
y_pred

array([28.47484944, 10.18883887, 37.04245196, 10.88598841, 33.20144117,
       28.78602787, 29.78635596, 28.60681005, 38.61819947, 32.58940066,
       26.62526114, 32.33443474, 36.86921179, 21.89668696, 36.85060276,
       36.93306929, 18.43739842, 18.73664378, 36.93140234, 30.6717812 ,
       27.71908612, 28.26307961, 32.60827519, 20.90870257, 32.39099402,
       18.69796775, 21.10381894, 29.82277966, 36.8469769 , 37.65798635,
       30.07541534, 28.86576369, 27.1966572 , 43.49967416, 30.54675784,
       12.54786283, 20.71688779, 30.58120989, 35.43989511, 20.54145036,
       29.33528409, 32.04729482, 22.22296732, 23.8209289 , 29.04720572,
       37.67436756, 28.84729148, 37.21099193, 30.36620624, 34.27404812,
       29.50053176, 28.81278376, 26.63177501, 28.4544141 , 29.7031166 ,
       39.31685051, 22.70625351, 28.79150197, 36.94331764, 14.52437212,
       27.09135561, 18.6535235 , 38.37248866, 24.15232369, 29.75169197,
       28.96106464, 37.17125699, 32.31125602, 19.60053112, 33.66

In [98]:
y_test

408    21.0
85     33.0
23     28.0
686    14.0
861    21.0
       ... 
66     29.0
142    24.0
486    35.0
258    35.0
682    20.0
Name: Age, Length: 72, dtype: float64

In [99]:
titanic=titanic.dropna()

In [100]:
x=titanic.iloc[:,1:9]
y=titanic.iloc[:,0]
scaler=StandardScaler()
scaled_titanic_x=scaler.fit_transform(x)

In [101]:
scaled_titanic_x

array([[ 0.90859974, -0.52766856,  0.52251079, ...,  0.92007841,
         0.51958818,  0.75613751],
       [-1.48298257,  0.57709388,  0.52251079, ...,  1.27975046,
        -2.04948671, -1.32251077],
       [ 0.90859974, -0.25147795, -0.55271372, ...,  1.63942251,
         0.51958818, -1.32251077],
       ...,
       [-1.48298257, -0.73481151, -0.55271372, ..., -1.5877719 ,
         0.51958818, -1.32251077],
       [-1.48298257, -0.25147795, -0.55271372, ..., -1.61733399,
        -2.04948671,  0.75613751],
       [ 0.90859974,  0.16280796, -0.55271372, ...,  0.63923859,
        -0.76494927,  0.75613751]])

In [125]:
x_train,x_test,y_train,y_test=_split.train_test_split(scaled_titanic_x,y,test_size=0.2,random_state=70)

In [126]:
model=RandomForestClassifier(n_estimators=200,n_jobs=10)
model.fit(x_train,y_train)

y_pred=model.predict(x_test)
score=accuracy_score(y_test,y_pred)
score

0.8251748251748252

In [127]:
y_pred

array([0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0], dtype=int64)

In [128]:
titanic_test=pd.read_csv('titanic_test.csv')

In [131]:
#titanic['Cabin']
def checking_blank_titanic_test(column):
    count=0
    for i in titanic_test[column]:
        #print(i)
        if str(i)=='nan':
            count+=1
    return count        
print(checking_blank_titanic_test('Cabin')) 

327


In [136]:
titanic_test=titanic_test.drop(columns='Name')

In [137]:
titanic_test=titanic_test.drop(columns='PassengerId')

In [138]:
ticket=LabelEncoder()
titanic_test['Tickets']=ticket.fit_transform(titanic_test['Ticket'])

In [139]:
titanic_test=titanic_test.drop(columns='Cabin')

In [140]:
print(len(titanic_test['Tickets'].unique()))
titanic_test=titanic_test.dropna(subset=['Embarked'])

363


In [141]:
embark=LabelEncoder()
titanic_test['Embarkeds']=embark.fit_transform(titanic_test['Embarked'])

In [142]:
se=LabelEncoder()
titanic_test['sex']=se.fit_transform(titanic_test['Sex'])

In [143]:
titanic_test=titanic_test.drop(columns=['Ticket','Embarked','Sex'])

In [144]:
titanic_test

Pclass   Age  SibSp  Parch      Fare  Tickets  Embarkeds  sex
0         3  34.5      0      0    7.8292      152          1    1
1         3  47.0      1      0    7.0000      221          2    0
2         2  62.0      0      0    9.6875       73          1    1
3         3  27.0      0      0    8.6625      147          2    1
4         3  22.0      1      1   12.2875      138          2    0
..      ...   ...    ...    ...       ...      ...        ...  ...
413       3   NaN      0      0    8.0500      267          2    1
414       1  39.0      0      0  108.9000      324          0    0
415       3  38.5      0      0    7.2500      346          2    1
416       3   NaN      0      0    8.0500      220          2    1
417       3   NaN      1      1   22.3583      105          0    1

[418 rows x 8 columns]

In [148]:
print(checking_blank_titanic_test('Age'))
print(checking_blank_titanic_test('SibSp'))
print(checking_blank_titanic_test('Parch'))
print(checking_blank_titanic_test('Tickets'))
print(checking_blank_titanic_test('Fare'))
print(checking_blank_titanic_test('Pclass'))
print(checking_blank_titanic_test('sex'))
print(checking_blank_titanic_test('Embarkeds'))

86
0
0
0
1
0
0
0


In [151]:
titanic_test=titanic_test.fillna(titanic_test.mean())

In [152]:
print(checking_blank_titanic_test('Age'))
print(checking_blank_titanic_test('SibSp'))
print(checking_blank_titanic_test('Parch'))
print(checking_blank_titanic_test('Tickets'))
print(checking_blank_titanic_test('Fare'))
print(checking_blank_titanic_test('Pclass'))
print(checking_blank_titanic_test('sex'))
print(checking_blank_titanic_test('Embarkeds'))

0
0
0
0
0
0
0
0


In [154]:
x=titanic_test.iloc[:,0:8]
#y=titanic.iloc[:,0]
scaler=StandardScaler()
scaled_titanic_test_x=scaler.fit_transform(x)

In [155]:
scaled_titanic_test_x

array([[ 0.87348191,  0.3349926 , -0.49947002, ..., -0.26949361,
        -0.47091535,  0.75592895],
       [ 0.87348191,  1.32553003,  0.61699237, ...,  0.37293425,
         0.70076689, -1.32287566],
       [-0.31581919,  2.51417495, -0.49947002, ..., -1.00502694,
        -0.47091535,  0.75592895],
       ...,
       [ 0.87348191,  0.65196458, -0.49947002, ...,  1.53675282,
         0.70076689,  0.75592895],
       [ 0.87348191,  0.        , -0.49947002, ...,  0.3636237 ,
         0.70076689,  0.75592895],
       [ 0.87348191,  0.        ,  0.61699237, ..., -0.70708939,
        -1.64259759,  0.75592895]])

In [156]:
y_pred=model.predict(scaled_titanic_test_x)

In [158]:
y_pred.shape

(418,)